//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistribucionRutas.Consultas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlConductores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlConductores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistribucionRutas.Consultas.SqlConductores", typeof(SqlConductores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update conductores set TipoLicencia = &apos;{0}&apos;, idHorario = &apos;{1}&apos;, 
        ///LimiteParadas = &apos;{2}&apos;, UsuarioModifico = &apos;{3}&apos;, FechaModifico = CURRENT_TIMESTAMP where
        ///Licencia = &apos;{4}&apos;;.
        /// </summary>
        internal static string ActualizarConductores {
            get {
                return ResourceManager.GetString("ActualizarConductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update conductores set estado = {0}, usuarioModifico = &apos;{2}&apos;, fechaModifico = current_timestamp where licencia = &apos;{1}&apos;;.
        /// </summary>
        internal static string CambiarEstadoConductores {
            get {
                return ResourceManager.GetString("CambiarEstadoConductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select count(1) conductores from Conductores where CONCAT(Licencia, Usuario) Like &apos;%{0}%&apos;;.
        /// </summary>
        internal static string CuentaConductores {
            get {
                return ResourceManager.GetString("CuentaConductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insert into Conductores(Licencia, TipoLicencia, idHorario, LimiteParadas, Usuario, Estado, UsuarioCreo, FechaCreo)
        ///values(&apos;{0}&apos;, &apos;{1}&apos;, {2}, &apos;{3}&apos;, &apos;{4}&apos;, 1, &apos;{5}&apos;, CURRENT_TIMESTAMP);.
        /// </summary>
        internal static string InsertaConductores {
            get {
                return ResourceManager.GetString("InsertaConductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select ROW_NUMBER() OVER(Order by Conductores.FechaCreo ASC) as Numero,
        ///Conductores.*
        ///from Conductores
        ///where CONCAT(Licencia, Usuario) Like &apos;%{0}%&apos;
        ///order by Numero
        ///OFFSET {1} ROWS FETCH NEXT {2} ROWS ONLY;.
        /// </summary>
        internal static string ObtieneConductores {
            get {
                return ResourceManager.GetString("ObtieneConductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select idHorario from horarios where estado = 1;.
        /// </summary>
        internal static string ObtieneHorarios {
            get {
                return ResourceManager.GetString("ObtieneHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select usuario from usuarios 
        ///where idRol = &apos;2&apos; and usuario not in (select usuario from conductores) and estado = 1.
        /// </summary>
        internal static string ObtieneUsuariosConductores {
            get {
                return ResourceManager.GetString("ObtieneUsuariosConductores", resourceCulture);
            }
        }
    }
}
