//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistribucionRutas.Consultas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlProductos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlProductos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistribucionRutas.Consultas.SqlProductos", typeof(SqlProductos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update productos set PesoProducto = &apos;{0}&apos;, UsuarioModifico = &apos;{1}&apos;
        ///where IdProducto = &apos;{2}&apos;.
        /// </summary>
        internal static string ActualizaRegistro {
            get {
                return ResourceManager.GetString("ActualizaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update productos set Estado = {0}, UsuarioModifico = &apos;{1}&apos;
        ///where IdProducto = &apos;{2}&apos;.
        /// </summary>
        internal static string CambiaEstadoRegistro {
            get {
                return ResourceManager.GetString("CambiaEstadoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select count(1) from Productos
        ///where CONCAT(NombreProducto, TipoProducto) Like &apos;%{0}%&apos;
        ///and estado = 1.
        /// </summary>
        internal static string CuentaRegistro {
            get {
                return ResourceManager.GetString("CuentaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a delete proveedorProducto where IdProveedor = {0} and IdProducto = {1}.
        /// </summary>
        internal static string EliminaProveedorProducto {
            get {
                return ResourceManager.GetString("EliminaProveedorProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insert into ProveedorProducto (IdProveedor, IdProducto, PrecioProducto, Existencia, Estado, UsuarioCreo, FechaCreo)
        ///values ({0}, {1}, {2}, {3}, 1, &apos;{4}&apos;, CURRENT_TIMESTAMP).
        /// </summary>
        internal static string InsertaProveedorProducto {
            get {
                return ResourceManager.GetString("InsertaProveedorProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insert into Productos(NombreProducto, TipoProducto, PesoProducto, Estado, UsuarioCreo, FechaCreo)
        ///values(&apos;{0}&apos;, &apos;{1}&apos;,{2}, 1, &apos;{3}&apos;, CURRENT_TIMESTAMP);.
        /// </summary>
        internal static string InsertaRegistro {
            get {
                return ResourceManager.GetString("InsertaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select ROW_NUMBER() OVER(Order by FechaCreo ASC) as Numero,
        ///Productos.*
        ///from Productos
        ///where CONCAT(NombreProducto, TipoProducto) Like &apos;%{0}%&apos;
        ///and estado = 1
        ///order by Numero
        ///OFFSET {1} ROWS FETCH NEXT {2} ROWS ONLY;.
        /// </summary>
        internal static string ObtieneDatos {
            get {
                return ResourceManager.GetString("ObtieneDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select * from proveedor where estado = 1.
        /// </summary>
        internal static string ObtieneProveedores {
            get {
                return ResourceManager.GetString("ObtieneProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///ROW_NUMBER() OVER(Order by proveedorProducto.FechaCreo ASC) as Numero,
        ///proveedor.NombreProveedor,
        ///productos.NombreProducto,
        ///proveedorProducto.PrecioProducto,
        ///proveedorProducto.Existencia,
        ///proveedorProducto.UsuarioCreo,
        ///proveedorProducto.FechaCreo,
        ///proveedorProducto.Estado,
        ///proveedorProducto.IdProducto,
        ///proveedorProducto.IdProveedor
        ///from proveedorProducto
        ///inner join proveedor 
        ///on proveedorProducto.IdProveedor = proveedor.IdProveedor
        ///inner join productos
        ///on productos.idProducto = provee [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ObtieneProveedorProducto {
            get {
                return ResourceManager.GetString("ObtieneProveedorProducto", resourceCulture);
            }
        }
    }
}
