//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistribucionRutas.Consultas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlTipoVehiculo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlTipoVehiculo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistribucionRutas.Consultas.SqlTipoVehiculo", typeof(SqlTipoVehiculo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update TipoVehiculos set CapacidadPeso = &apos;{0}&apos;, KMXGalon = &apos;{1}&apos;, Galones = &apos;{2}&apos;,Descripcion = &apos;{3}&apos;, UsuarioModifico = &apos;{4}&apos;, FechaModifico = CURRENT_TIMESTAMP, TipoGas = &apos;{6}&apos;
        ///where IdTipoVehiculo = &apos;{5}&apos;.
        /// </summary>
        internal static string ActualizaRegistro {
            get {
                return ResourceManager.GetString("ActualizaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update TipoVehiculos set Estado = &apos;{0}&apos;, usuarioModifico = &apos;{1}&apos;, FechaModifico = CURRENT_TIMESTAMP 
        ///where IdTipoVehiculo = &apos;{2}&apos;.
        /// </summary>
        internal static string CambiaEstadoRegistro {
            get {
                return ResourceManager.GetString("CambiaEstadoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select count(1) from tipoVehiculos where
        /// CONCAT(Descripcion, TipoGas) Like &apos;%{0}%&apos;
        ///and estado = 1;.
        /// </summary>
        internal static string CuentaRegistro {
            get {
                return ResourceManager.GetString("CuentaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insert into TipoVehiculos(CapacidadPeso, KMXGalon, Galones, TipoGas, Descripcion, Estado, UsuarioCreo, FechaCreo)
        ///Values (&apos;{0}&apos;,&apos;{1}&apos;,&apos;{2}&apos;,&apos;{3}&apos;,&apos;{4}&apos;,1, &apos;{5}&apos;, CURRENT_TIMESTAMP).
        /// </summary>
        internal static string InsertaRegistro {
            get {
                return ResourceManager.GetString("InsertaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select ROW_NUMBER() OVER(Order by TipoVehiculos.FechaCreo ASC) as Numero,
        ///TipoVehiculos.*
        ///from TipoVehiculos
        ///where CONCAT(Descripcion, TipoGas) Like &apos;%{0}%&apos;
        ///and estado = 1
        ///order by IdTipoVehiculo
        ///OFFSET {1} ROWS FETCH NEXT {2} ROWS ONLY;.
        /// </summary>
        internal static string ObtieneDatos {
            get {
                return ResourceManager.GetString("ObtieneDatos", resourceCulture);
            }
        }
    }
}
