//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistribucionRutas.Consultas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlUsuarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlUsuarios() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistribucionRutas.Consultas.SqlUsuarios", typeof(SqlUsuarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE Usuarios SET IdRol = {0}, UsuarioModifico = &apos;{2}&apos;, FechaModifico = CURRENT_TIMESTAMP() where Usuario = &apos;{1}&apos;;.
        /// </summary>
        internal static string AsignaRolUsuario {
            get {
                return ResourceManager.GetString("AsignaRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE Usuarios SET Estado = {2}, UsuarioModifico = &apos;{1}&apos;, FechaModifico = CURRENT_TIMESTAMP() where Usuario = &apos;{0}&apos;;.
        /// </summary>
        internal static string DesactivaUsuario {
            get {
                return ResourceManager.GetString("DesactivaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select * from Roles Where estado =1.
        /// </summary>
        internal static string ObtieneRoles {
            get {
                return ResourceManager.GetString("ObtieneRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Usuarios.*, Roles.Descripcion as Rol From Usuarios 
        ///inner join Roles
        ///	on Usuarios.IdRol = Roles.IdRol
        ///Where Usuarios.Estado = 1
        ///Order By Usuarios.usuario
        ///OFFSET {0} ROWS FETCH NEXT {1} ROWS ONLY.
        /// </summary>
        internal static string ObtieneUsuarios {
            get {
                return ResourceManager.GetString("ObtieneUsuarios", resourceCulture);
            }
        }
    }
}
