//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistribucionRutas.Consultas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlVehiculos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlVehiculos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistribucionRutas.Consultas.SqlVehiculos", typeof(SqlVehiculos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update Vehiculos set Placa = &apos;{0}&apos;, LicenciaConductor = &apos;{1}&apos;, idTipoVehiculo = &apos;{2}&apos;, UsuarioModifico = &apos;{3}&apos;, FechaModifico = CURRENT_TIMESTAMP
        ///where Placa = &apos;{4}&apos;;.
        /// </summary>
        internal static string ActualizaRegistro {
            get {
                return ResourceManager.GetString("ActualizaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update Vehiculos set Estado = {0}, UsuarioModifico = &apos;{1}&apos;, FechaModifico = CURRENT_TIMESTAMP
        ///where Placa = &apos;{2}&apos;;.
        /// </summary>
        internal static string CambiaEstadoRegistro {
            get {
                return ResourceManager.GetString("CambiaEstadoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select count(1) from vehiculos where CONCAT(Placa, LicenciaConductor) Like &apos;%{0}%&apos;
        ///and estado = 1.
        /// </summary>
        internal static string CuentaRegistro {
            get {
                return ResourceManager.GetString("CuentaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert into Vehiculos(Placa, KmRecorridos, LicenciaConductor, idTipoVehiculo, Estado, UsuarioCreo, FechaCreo)
        ///values (&apos;{0}&apos;, {1}, &apos;{2}&apos;, {3}, 1, &apos;{4}&apos;, CURRENT_TIMESTAMP);.
        /// </summary>
        internal static string InsertaRegistro {
            get {
                return ResourceManager.GetString("InsertaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select * from Conductores where Licencia not in (select LicenciaConductor from vehiculos where licencia = Conductores.Licencia and estado = 1) and estado = 1;.
        /// </summary>
        internal static string ObtieneConductores {
            get {
                return ResourceManager.GetString("ObtieneConductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select ROW_NUMBER() OVER(Order by FechaCreo ASC) as Numero,
        ///vehiculos.*
        ///from vehiculos
        ///where CONCAT(Placa, LicenciaConductor) Like &apos;%{0}%&apos;
        ///and estado = 1
        ///order by Numero
        ///OFFSET {1} ROWS FETCH NEXT {2} ROWS ONLY;.
        /// </summary>
        internal static string ObtieneDatos {
            get {
                return ResourceManager.GetString("ObtieneDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM TipoVehiculos where estado = 1;.
        /// </summary>
        internal static string ObtieneTiposVehiculo {
            get {
                return ResourceManager.GetString("ObtieneTiposVehiculo", resourceCulture);
            }
        }
    }
}
